<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:08:52.
 */
class admin_configuracaoModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var admin_configuracaoModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new admin_configuracaoModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers admin_configuracaoModel::setConfigType
     * @todo   Implement testSetConfigType().
     */
    public function testSetConfigType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::selecionar
     * @todo   Implement testSelecionar().
     */
    public function testSelecionar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::selecionar_plugin_config
     * @todo   Implement testSelecionar_plugin_config().
     */
    public function testSelecionar_plugin_config() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::get_config_by_plugin
     * @todo   Implement testGet_config_by_plugin().
     */
    public function testGet_config_by_plugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::editar_plugin
     * @todo   Implement testEditar_plugin().
     */
    public function testEditar_plugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::hasConfigurationFile
     * @todo   Implement testHasConfigurationFile().
     */
    public function testHasConfigurationFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::getConf
     * @todo   Implement testGetConf().
     */
    public function testGetConf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::editar
     * @todo   Implement testEditar().
     */
    public function testEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::getModelName
     * @todo   Implement testGetModelName().
     */
    public function testGetModelName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::getModelLabel
     * @todo   Implement testGetModelLabel().
     */
    public function testGetModelLabel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_configuracaoModel::getModelDescription
     * @todo   Implement testGetModelDescription().
     */
    public function testGetModelDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
