<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:04.
 */
class admin_recursoModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var admin_recursoModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new admin_recursoModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers admin_recursoModel::ListarRecursos
     * @todo   Implement testListarRecursos().
     */
    public function testListarRecursos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_recursoModel::menuRecursos
     * @todo   Implement testMenuRecursos().
     */
    public function testMenuRecursos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_recursoModel::getResources
     * @todo   Implement testGetResources().
     */
    public function testGetResources() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_recursoModel::getJsplugins
     * @todo   Implement testGetJsplugins().
     */
    public function testGetJsplugins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_recursoModel::getRecVar
     * @todo   Implement testGetRecVar().
     */
    public function testGetRecVar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_recursoModel::getJsVar
     * @todo   Implement testGetJsVar().
     */
    public function testGetJsVar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_recursoModel::getModelName
     * @todo   Implement testGetModelName().
     */
    public function testGetModelName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_recursoModel::getModelLabel
     * @todo   Implement testGetModelLabel().
     */
    public function testGetModelLabel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_recursoModel::getModelDescription
     * @todo   Implement testGetModelDescription().
     */
    public function testGetModelDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
