<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:03.
 */
class admin_templateModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var admin_templateModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new admin_templateModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers admin_templateModel::listTemplates
     * @todo   Implement testListTemplates().
     */
    public function testListTemplates() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
