<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:08:56.
 */
class admin_installModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var admin_installModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new admin_installModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers admin_installModel::install
     * @todo   Implement testInstall().
     */
    public function testInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::unstall
     * @todo   Implement testUnstall().
     */
    public function testUnstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::disable
     * @todo   Implement testDisable().
     */
    public function testDisable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::enable
     * @todo   Implement testEnable().
     */
    public function testEnable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::populate
     * @todo   Implement testPopulate().
     */
    public function testPopulate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::init
     * @todo   Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::updatePluginModels
     * @todo   Implement testUpdatePluginModels().
     */
    public function testUpdatePluginModels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::getPluginStatus
     * @todo   Implement testGetPluginStatus().
     */
    public function testGetPluginStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::listarPlugins
     * @todo   Implement testListarPlugins().
     */
    public function testListarPlugins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers admin_installModel::inserirPlugin
     * @todo   Implement testInserirPlugin().
     */
    public function testInserirPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
